### ISSUE TITLE
mpl_moroz : масштаб по осям

### ISSUE THREAD

**Issue by avasyukov** [leeiozh/python3sem#1]
Сейчас масштаб по осям сильно разный по OX и по OY. В итоге, например, длинная и тонкая область визуально выглядит как почти квадратик. А условный кружочек превращается в эллипс.

В условии было, что масштаб должен быть зафиксирован. Это нужно поправить.

**Comment by leeiozh** [comment]
Не осознала. Кружочек он и есть кружочек, при любом растягивании plt.show его оставляет кружочком. 
Здесь предлагается ax.set_ylimом подогнать под одинаковый масштаб или как?

**Comment by avasyukov** [comment]
Имеется в виду следующее. Например, вот здесь - http://judge2.vdi.mipt.ru/ejudge/lab_01_mpl/003.png - три точки слева лежат примерно на дуге окружности. И при взгляде глазами на картинку это видно. А на третьем графике лабы сейчас - совсем не видно.

Цитата из постановки: "общая геометрия области должна быть передана (например, длинная область должна быть длинной, а не растянутой в квадрат)".

Подгонять руками лимиты по осям лично я бы не стал, я бы зафиксировал равный масштаб по OX и OY.

**Comment by leeiozh** [comment]
Теперь осознала. То есть мы не должны забывать, что это карта местности)

**Comment by avasyukov** [comment]
Да. Но нет.

Задача понята корректно. Движения в коде в разумную сторону. Но график остался искажённым.
