### ISSUE TITLE
mpl_moroz : переносимость кода

### ISSUE THREAD

**Issue by avasyukov** [leeiozh/python3sem#2]
(Этого не было в материалах. И это почти офтоп. Но тем не менее.)

Вот эта строчка:
https://github.com/leeiozh/python3sem/blob/4ec19578fc8e1d2ac4703147b1442d9460d812de/mpl_lab/mpl_moroz.py#L11
внезапно не переносима между разными операционными системами.

Потому что разделитель элементов пути по ФС разный в разных ОС. Идейно верно примерно вот так: `os.path.join("data", "00" + str(i + 1) + ".dat")`.

**Comment by leeiozh** [comment]
Даа, я сталкивалась с этим
Погуглила, красиво
