### ISSUE TITLE
frames: рефактор

### ISSUE THREAD

**Issue by avasyukov** [leeiozh/python3sem#3]
Не ошибка. Но всё-таки очень тянутся руки вот этот кусочек:
https://github.com/leeiozh/python3sem/blob/4ec19578fc8e1d2ac4703147b1442d9460d812de/mpl_lab/frames.py#L3-L10

Переписать вот так:
```
x = []
with open("frames.dat", 'r') as file:
    for i, line in enumerate(file):
        x.append([float(num) for num in line.split()])
```

Заодно полностью снимается прибитое гвоздями ограничение на количество кадров.

**Comment by leeiozh** [comment]
Исправлено, красиво
