### ISSUE TITLE
marks : чтение входных данных

### ISSUE THREAD

**Issue by avasyukov** [leeiozh/python3sem#4]
Давайте допилимся до состояния, когда имена препов и номера групп в файле могут быть любыми. Т.е. их нельзя жёстко пронумеровать и прибить префиксы гвоздями, их нужно именно считать, ожидая там произвольные строки.

Upd: и оценки тоже могут быть любые. И даже 1 может быть.

(А если после этого в коде всё-таки останутся волшебные константы, их стоит сделать именованными константами, зафиксированными один раз, без волшебных цифр загадочного происхожения по разным строчкам кода.)

**Comment by leeiozh** [comment]
допилила до состояния, когда 0 - минимальная оценка, howmanymarks - максимальная
если нужно вообще без ограничений - сделаю

**Comment by avasyukov** [comment]
Нынешний вид - ок.
