### ISSUE TITLE
numpy / eq - вид матрицы

### ISSUE THREAD

**Issue by avasyukov** [leeiozh/python3sem#6]
Вот тут матрица собралась не совсем корректно:
https://github.com/leeiozh/python3sem/blob/6ef8af973293b30aac567a0dd3b08c73c3d45f0c/numpy0911/eq.py#L10-L13

В итоге волна ушла направо, а слева не вернулась. Ну и формально расчёт несколько отличался от нужного, но это глазами не заметно уже.

**Comment by leeiozh** [comment]
Я оочень долго пыталась понять, почему волна не возвращалась слева. Дописывала что-то по типу `output_data[i, 0] = output_data[i - 1, -1]`, а оказалось все так просто...

**Comment by avasyukov** [comment]
Да, починено
