### ISSUE TITLE
numpy / signal - скорость работы

### ISSUE THREAD

**Issue by avasyukov** [leeiozh/python3sem#7]
Это полностью правильная логика:
https://github.com/leeiozh/python3sem/blob/6ef8af973293b30aac567a0dd3b08c73c3d45f0c/numpy0911/signal_filter.py#L9-L13

Но от for-а придётся всё же избавиться, по крайней мере для основной части массива.

Можно посмотреть на `cumsum` или `convolve`. Или можно применить магию слайсов такого духа:
```
# это не логика из задачи, просто техническая демка, что можно делать со слайсами
z = np.arange(10)
z[:-1] = z[:-1] + z[1:]
print(z)
```

**Comment by leeiozh** [comment]
Если использовать слайсы, можно ли как-то без for сделать быструю сумму? Сейчас это выглядит очень не гибко, но я не оч понимаю, как сделать это суммирование слайсами быстро.

**Comment by leeiozh** [comment]
ну то есть `output_data[9:] = (input_data[:-9] + input_data[1:-8] + input_data[2:-7] + input_data[3:-6] + input_data[4:-5] +
                   input_data[5:-4] + input_data[6:-3] + input_data[7:-2] + input_data[8:-1] + input_data[9:]) / 9` не кажется мне оптимальным, а хочется таки реализовать это через слайсы

**Comment by avasyukov** [comment]
Можно обсудить это вживую. Но сейчас стало формально ок. Только ещё 9 на 10 заменить в знаменателе.
